package com.example.arib.ftcscoring;

import android.content.Context;
import android.widget.Toast;

import java.util.ArrayList;

/**
 * Created by dhuka_844963 on 1/13/2016.
 */
public class Team {
    //variables that define a team
    double MMR;
    //int[] matchScores;
    ArrayList<Integer> matchScores;
    double pitScore;
    int teamNumber;
    int id;
    String teamName;
    String notes;

    //contructor for basic team sets everything to 0 and sets id to next available
    public Team() {
        id = MainActivity.getNextAvailId();
        MMR = 0;
//        matchScores = new int[5];
        matchScores = new ArrayList<>();
        teamName = "";
        pitScore = 0.0;
        teamNumber = 0;
        notes = "";
    }
    //creates a team based on their first match
    public Team(int score, int teamNumber) {
//        matchScores = new int[5];
//        matchScores[0] = score;
        matchScores = new ArrayList<>();
        matchScores.add(score);
        teamName = "";
        this.teamNumber = teamNumber;
        id = MainActivity.getNextAvailId();
        MMR = 0;
        notes = "";
    }

    //creates a team based on their first pit score
    public Team(double score, int teamNumber, String notes, String teamName) {
//        matchScores = new int[5];
        matchScores = new ArrayList<>();
        pitScore = score;
        this.teamName = teamName;
        this.teamNumber = teamNumber;
        MMR = 0;
        id = MainActivity.getNextAvailId();
        this.notes = notes;
    }

    //calculates a teams MMR
    public void calculateMMR() {
        //data that will calculate the mmr
        int average = 0;
        boolean okSoFar = true;
        int consistency;
        //calculate the average and do nothing if they havent played matches
        if(matchScores.size() > 0) {
            for(int i = 0; i < matchScores.size(); i++) {
                average += matchScores.get(i);
            }
            average = average / matchScores.size();
        } else {
            okSoFar = false;
            Context context = MainActivity.mainContext;
            CharSequence text = "Error Occured";
            int duration = Toast.LENGTH_SHORT;

            Toast toast = Toast.makeText(context, text, duration);
            toast.show();
        }
        //starting minimum score and maximum score to get the range of scores
        int minimumScore = Integer.MAX_VALUE;
        int maximumScore = Integer.MIN_VALUE;
        if(okSoFar && matchScores.size() > 1) {
            for(int i = 0; i < matchScores.size(); i++) {
                if(matchScores.get(i) < minimumScore) {
                    minimumScore = matchScores.get(i);
                }
                if(matchScores.get(i) > maximumScore) {
                    maximumScore = matchScores.get(i);
                }
            }
            //calculate the consistency based on range of scores
            consistency = maximumScore - minimumScore;
            consistency = consistency / 10;
            consistency = Math.abs((maximumScore / 2) - consistency);

        }   //if an error occurs do not calculate
        else {
            consistency = 0;
            maximumScore = matchScores.get(0);

        }
        //if calculations went properly
        if(okSoFar) {
            //set the score
            double scoreToAdd = 0;
            scoreToAdd += average;
            scoreToAdd += maximumScore / 2;
            scoreToAdd += consistency;
            MMR = scoreToAdd;
        }

    }

    //add a match score to the teams played matches
    public boolean addMatchScore(int score) {
        int spot = 0;
        boolean found = false;
        for(int i = 0; i < matchScores.size(); i++) {
            if(matchScores.get(i) == 0 && !found) {
                spot = i;
                found = true;
            }
        }
        if(spot + 1 == 5) {
            return false;
        }
        else {
            matchScores.add(score);
            return true;
        }
    }

    //gets the size of the array list
    private int getUsedSize() {
        int spot = 0;
        boolean found = false;
        for(int i = 0; i < matchScores.size(); i++) {
            if(matchScores.get(i) == 0 && !found) {
                spot = i;
                found = true;
            }
        }
        return spot + 1;
    }

    //AUTOGENERATED: setters and getters for all the variables
    public int getTeamNumber() {
        return teamNumber;
    }

    public double getMMR() {
        return MMR;
    }

    public void setMMR(double MMR) {
        this.MMR = MMR;
    }

    public ArrayList<Integer> getMatchScores() {
        return matchScores;
    }

    public void setMatchScores(ArrayList<Integer> matchScores) {
        this.matchScores = matchScores;
    }

    public double getPitScore() {
        return pitScore;
    }

    public void setPitScore(double pitScore) {
        this.pitScore = pitScore;
    }

    public void setTeamNumber(int teamNumber) {
        this.teamNumber = teamNumber;
    }
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setInfo(String message) {
        notes = message;
    }

    public String getInfo() {
        return notes;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
}